Repository it-top-shambala/Logger, pull requests merged in 2022-08, with the labels that each got.

#6 добавил в проект документацию со специальными комментариями
  .editorconfig
  Logger/Console/ConsoleColorConfig.cs
  Logger/Console/LogToConsole.cs
  Logger/Doc/logger_doc.xml
  Logger/File/LogToFile.cs
  Logger/File/PathFileConfig.cs
  Logger/ILogger.cs
  Logger/Logger.csproj
Labels: documentation

#12 Documentation
  README.md
Labels: documentation

#9 Refactoring
  Logger/Console/ConsoleColorConfig.cs
  Logger/File/LogToFile.cs
  Logger/File/PathFileConfig.cs
  README.md
Labels: refactoring

#13 Добавление релиза v0.2
  .editorconfig
  .github/workflows/sonar_cloud.yml
  .gitignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  LICENSE
  LICENSE_RU
  Logger/Console/ConsoleColorConfig.cs
  Logger/Console/LogToConsole.cs
  Logger/Doc/logger_doc.xml
  Logger/File/LogToFile.cs
  Logger/File/PathFileConfig.cs
  Logger/ILogger.cs
  Logger/Logger.csproj
  README.md
  dist/Logger.deps.json
  dist/Logger.dll
Labels: release

#14 Release v0.2
  .editorconfig
  .github/workflows/sonar_cloud.yml
  .gitignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  LICENSE
  LICENSE_RU
  Logger/Console/ConsoleColorConfig.cs
  Logger/Console/LogToConsole.cs
  Logger/Doc/logger_doc.xml
  Logger/File/LogToFile.cs
  Logger/File/PathFileConfig.cs
  Logger/ILogger.cs
  Logger/Logger.csproj
  README.md
  dist/Logger.deps.json
  dist/Logger.dll
Labels: release
